include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
    unused_import: error
    unused_element: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    - comment_references
    - prefer_generic_function_type_aliases
    - prefer_typing_uninitialized_variables
    - unnecessary_const
    - unnecessary_new
